Repository Aled-Inc/Aled, pull requests merged in 2024-09, with the labels that each got.

#49 Feature/28 product caroussel
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/en.json
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/fr.json
  react-native/assets/icons/empty_box.svg
  react-native/src/components/Caroussels/SimpleProductCaroussel.js
  react-native/src/screens/Home/HomeScreen.js
  react-native/src/styles/HomeStyle.js
Labels: enhancement, FrontEnd, localizations

#52 Feature/27 product list
  aspnet-core/src/Aled.Application.Contracts/Inventories/Dtos/InventoryDetailsDto.cs
  aspnet-core/src/Aled.Application.Contracts/Inventories/Dtos/InventoryDto.cs
  aspnet-core/src/Aled.Application.Contracts/Inventories/IInventoryAppService.cs
  aspnet-core/src/Aled.Application.Contracts/Products/Dtos/GetProductsDto.cs
  aspnet-core/src/Aled.Application.Contracts/Products/Dtos/NutrientsDto.cs
  aspnet-core/src/Aled.Application.Contracts/Products/Dtos/ProductDetailsDto.cs
  aspnet-core/src/Aled.Application/AledApplicationAutoMapperProfile.cs
  aspnet-core/src/Aled.Application/Inventories/InventoryAppService.cs
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/en.json
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/fr.json
  aspnet-core/src/Aled.Domain/Managers/Inventories/IInventoryManager.cs
  aspnet-core/src/Aled.Domain/Managers/Inventories/InventoryManager.cs
  aspnet-core/src/Aled.Domain/Repositories/Products/IProductRepository.cs
  aspnet-core/src/Aled.EntityFrameworkCore/EfCoreRepositories/Products/EfCoreProductRepository.cs
  aspnet-core/src/Aled.HttpApi.Client/ClientProxies/Aled/OpenFoodFactService/Products/Dtos/NutrientsDto.cs
  aspnet-core/src/Aled.HttpApi.Client/ClientProxies/Aled/OpenFoodFactService/Products/Dtos/ProductDetailsDto.cs
  aspnet-core/src/Aled.HttpApi.Client/ClientProxies/app-generate-proxy.json
  react-native/package.json
  react-native/src/Filters/FiltersComponent.js
  react-native/src/api/InventoryAPI.js
  react-native/src/components/Cards/ProductCards/ProductCardComponent.js
  react-native/src/components/Cards/ProductCards/ProductImageCardComponent.js
  react-native/src/components/Cards/ProductCards/ScannedProductCardComponent.js
  react-native/src/components/Caroussels/SimpleProductCaroussel.js
  react-native/src/components/Search/SearchProduct.js
  react-native/src/components/Tags/Tag.js
  react-native/src/navigators/BottomTabNavigator.js
  react-native/src/screens/Home/HomeScreen.js
  react-native/src/screens/Inventory/InventoryScreen.js
  react-native/src/screens/ProductDetails/NutritionTab.js
  react-native/src/screens/ProductDetails/ProductDetailScreen.js
  react-native/src/screens/Scan/ScannedProductSummary.js
  react-native/src/services/InventoryService.js
  react-native/src/store/actions/InventoryActions.js
  react-native/src/store/reducers/InventoryReducer.js
  react-native/src/store/sagas/AuthSaga.js
  react-native/src/store/sagas/InventorySaga.js
  react-native/src/store/selectors/InventorySelector.js
  react-native/src/styles/InventoryStyle.js
  react-native/src/utils/CommonUtils.js
  react-native/src/utils/InventoryUtils.js
  react-native/src/utils/ProductCategoryTagUtils.js
  react-native/src/utils/ProductUtils.js
  react-native/src/utils/SizeUtils.js
Labels: enhancement, Backend, FrontEnd, localizations

#54 Tech/53 clean front project
  react-native/App.js
  react-native/src/api/AccountAPI.js
  react-native/src/api/TenantManagementAPI.js
  react-native/src/components/AddIcon/AddIcon.js
  react-native/src/components/DataList/DataList.js
  react-native/src/components/DrawerContent/DrawerContent.js
  react-native/src/components/FormButtons/FormButtons.js
  react-native/src/components/FormButtons/index.js
  react-native/src/components/HamburgerIcon/HamburgerIcon.js
  react-native/src/components/Loading/Loading.js
  react-native/src/components/LoadingButton/LoadingButton.js
  react-native/src/components/Modals/ActionStatusModal.js
  react-native/src/components/Modals/BaseModal.js
  react-native/src/components/TenantBox/TenantBox.js
  react-native/src/hocs/PermissionHOC.js
  react-native/src/hooks/UsePermission.js
  react-native/src/screens/ChangePassword/ChangePasswordForm.js
  react-native/src/screens/ChangePassword/ChangePasswordScreen.js
  react-native/src/screens/CreateUpdateTenant/CreateUpdateTenantForm.js
  react-native/src/screens/CreateUpdateTenant/CreateUpdateTenantScreen.js
  react-native/src/screens/CreateUpdateUser/CreateUpdateUserForm.js
  react-native/src/screens/CreateUpdateUser/CreateUpdateUserScreen.js
  react-native/src/screens/CreateUpdateUser/UserRoles.js
  react-native/src/screens/ManageProfile/ManageProfileForm.js
  react-native/src/screens/ManageProfile/ManageProfileScreen.js
  react-native/src/screens/Tenants/TenantsScreen.js
Labels: FrontEnd

#56 Tech/55 add unit tests
  aspnet-core/src/Aled.Application/Account/AccountExtendedAppService.cs
  aspnet-core/src/Aled.Application/AledApplicationAutoMapperProfile.cs
  aspnet-core/src/Aled.Application/Products/ProductAppService.cs
  aspnet-core/src/Aled.Domain/AggregateRoots/Inventories/Inventory.cs
  aspnet-core/src/Aled.Domain/Managers/Inventories/InventoryManager.cs
  aspnet-core/src/Aled.Domain/Repositories/Inventories/IInventoryRepository.cs
  aspnet-core/src/Aled.EntityFrameworkCore/EfCoreRepositories/Inventories/EfCoreInventoryRepository.cs
  aspnet-core/test/Aled.Application.Tests/Aled.Application.Tests.csproj
  aspnet-core/test/Aled.Application.Tests/AledApplicationTestBase.cs
  aspnet-core/test/Aled.Application.Tests/AledApplicationTestModule.cs
  aspnet-core/test/Aled.Application.Tests/Fakes/Managers/IdentitySecurityLogManagerFake.cs
  aspnet-core/test/Aled.Application.Tests/Fakes/Managers/IdentityUserManagerFake.cs
  aspnet-core/test/Aled.Application.Tests/Fakes/Managers/UnitOfWorkManagerFake.cs
  aspnet-core/test/Aled.Application.Tests/Fakes/Services/ProductProxyAppServiceFake.cs
  aspnet-core/test/Aled.Application.Tests/UnitTests/Account/AccountExtendedAppServiceTests.cs
  aspnet-core/test/Aled.Application.Tests/UnitTests/Account/Profile/ProfileAppServiceTest.cs
  aspnet-core/test/Aled.Application.Tests/UnitTests/Email/EmailServiceTest.cs
  aspnet-core/test/Aled.Application.Tests/UnitTests/Inventories/InventoryAppServiceTest.cs
  aspnet-core/test/Aled.Application.Tests/UnitTests/Products/ProductAppServiceTest.cs
  aspnet-core/test/Aled.Domain.Tests/AledDomainTestModule.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/InMemoryBasicRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/InMemoryRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryBackgroundJobRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryIdentityLinkUserRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryIdentityRoleRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryIdentitySecurityLogRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryIdentityUserRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryInventoryBasicRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryOrganizationUnitRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryPermissionDefinitionRecordRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryPermissionGroupDefinitionRecordRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryProductRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemorySettingDefinitionRecordRepository.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryTenantRepository.cs
  aspnet-core/test/Aled.TestBase/AledTestBaseModule.cs
  aspnet-core/test/Aled.TestBase/Security/FakeCurrentPrincipalAccessor.cs
  aspnet-core/test/Aled.TestBase/Security/FakeCurrentUser.cs
Labels: Backend

#68 Add coming page :
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/en.json
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/fr.json
  react-native/assets/illustrations/soon.svg
  react-native/src/presentation/navigators/BottomTabNavigator.js
  react-native/src/presentation/screens/ComingSoon/ComingSoon.js
  react-native/src/presentation/screens/Profile/ProfileScreen.js
Labels: FrontEnd

#66 Replace N/A with product expiration date
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/en.json
  aspnet-core/src/Aled.Domain.Shared/Localization/Aled/fr.json
  react-native/src/presentation/components/Cards/ProductCards/ProductCardComponent.js
  react-native/src/presentation/components/Cards/ProductCards/ProductImageCardComponent.js
  react-native/src/presentation/components/Cards/ProductCards/ScannedProductCardComponent.js
  react-native/src/presentation/screens/ProductDetails/ProductDetailScreen.js
Labels: FrontEnd

#72 Fix multiple notifications
  react-native/App.js
  react-native/src/common/utils/NotificationUtils.js
  react-native/src/presentation/screens/Home/HomeScreen.js
Labels: bug, FrontEnd

#74 fix get products current user #73
  aspnet-core/src/Aled.Domain/Entities/Products/Product.cs
  aspnet-core/src/Aled.Domain/Managers/Inventories/InventoryManager.cs
  aspnet-core/src/Aled.Domain/Repositories/Products/IProductRepository.cs
  aspnet-core/src/Aled.EntityFrameworkCore/EfCoreRepositories/Products/EfCoreProductRepository.cs
  aspnet-core/test/Aled.Application.Tests/UnitTests/Inventories/InventoryAppServiceTest.cs
  aspnet-core/test/Aled.Domain.Tests/Fakes/Repositories/InMemoryProductRepository.cs
  react-native/src/presentation/screens/Home/HomeScreen.js
Labels: bug, Backend, FrontEnd
