Repository Aled-Inc/Aled, pull requests merged in 2024-07, with the labels that each got.

#17 Feature/7 login design
  aspnet-core/.gitignore
  aspnet-core/src/Aled.AuthServer/yarn.lock
  aspnet-core/src/Aled.Blazor/yarn.lock
  aspnet-core/src/Aled.Domain/OpenIddict/OpenIddictDataSeedContributor.cs
  aspnet-core/src/Aled.HttpApi.Client/Scripts/updateProxy.sh
  react-native/.gitignore
  react-native/assets/fonts/Inter-Black.ttf
  react-native/assets/fonts/Inter-Bold.ttf
  react-native/assets/fonts/Inter-ExtraBold.ttf
  react-native/assets/fonts/Inter-ExtraLight.ttf
  react-native/assets/fonts/Inter-Light.ttf
  react-native/assets/fonts/Inter-Medium.ttf
  react-native/assets/fonts/Inter-Regular.ttf
  react-native/assets/fonts/Inter-SemiBold.ttf
  react-native/assets/fonts/Inter-Thin.ttf
  react-native/package-lock.json
  react-native/package.json
  react-native/react-native.config.js
  react-native/src/navigators/AuthNavigator.js
  react-native/src/screens/Login/LoginScreen.js
Labels: enhancement, FrontEnd

#19 Add https supports + SSL certificate config
  aspnet-core/Aled.sln
  aspnet-core/src/Aled.Application/Inventories/InventoryAppService.cs
  aspnet-core/src/Aled.AuthServer/Aled.AuthServer.csproj
  aspnet-core/src/Aled.AuthServer/AledAuthServerModule.cs
  aspnet-core/src/Aled.AuthServer/Properties/launchSettings.json
  aspnet-core/src/Aled.AuthServer/appsettings.json
  aspnet-core/src/Aled.DbMigrator/appsettings.json
  aspnet-core/src/Aled.Domain/Services/OpenFoodFacts/OpenFoodFactService.cs
  aspnet-core/src/Aled.HttpApi.Client/Aled.HttpApi.Client.csproj
  aspnet-core/src/Aled.HttpApi.Client/AledHttpApiClientModule.cs
  aspnet-core/src/Aled.HttpApi.Client/ClientProxies/Aled/OpenFoodFactService/HealthCheckClientProxy.Generated.cs
  aspnet-core/src/Aled.HttpApi.Client/ClientProxies/Aled/OpenFoodFactService/HealthCheckClientProxy.cs
  aspnet-core/src/Aled.HttpApi.Client/ClientProxies/Aled/OpenFoodFactService/IHealthCheckAppService.cs
  aspnet-core/src/Aled.HttpApi.Client/ClientProxies/app-generate-proxy.json
  aspnet-core/src/Aled.HttpApi.Client/Scripts/updateProxy.sh
  aspnet-core/src/Aled.HttpApi.Client/updateProxy.sh
  aspnet-core/src/Aled.HttpApi.Host/Controllers/OpenFoodFactController.cs
  aspnet-core/src/Aled.HttpApi.Host/Properties/launchSettings.json
  aspnet-core/src/Aled.HttpApi.Host/appsettings.json
  aspnet-core/ssl/cert.conf
  aspnet-core/ssl/cert.crt
  aspnet-core/ssl/cert.pem
  aspnet-core/ssl/key.pem
  aspnet-core/test/Aled.HttpApi.Client.ConsoleTestApp/Aled.HttpApi.Client.ConsoleTestApp.csproj
  aspnet-core/test/Aled.HttpApi.Client.ConsoleTestApp/ConsoleTestAppHostedService.cs
  aspnet-core/test/Aled.HttpApi.Client.ConsoleTestApp/OpenFoodFacts/HealthCheckAppService.cs
  aspnet-core/test/Aled.HttpApi.Client.ConsoleTestApp/appsettings.json
  react-native/Environment.js
Labels: Backend

#18 Feature/9 register page
  react-native/src/api/AccountAPI.js
  react-native/src/navigators/AuthNavigator.js
  react-native/src/screens/Register/RegisterScreen.js
Labels: enhancement, FrontEnd

#20 séparation des appsetings pour la config
  aspnet-core/src/Aled.AuthServer/Aled.AuthServer.csproj
  aspnet-core/src/Aled.AuthServer/AledAuthServerModule.cs
  aspnet-core/src/Aled.AuthServer/appsettings.Development.json
  aspnet-core/src/Aled.AuthServer/appsettings.json
  aspnet-core/src/Aled.Blazor/Aled.Blazor.csproj
  aspnet-core/src/Aled.Blazor/appsettings.Development.json
  aspnet-core/src/Aled.Blazor/appsettings.json
  aspnet-core/src/Aled.HttpApi.Host/appsettings.Development.json
  aspnet-core/src/Aled.HttpApi.Host/appsettings.json
Labels: enhancement, Backend

#22 Fix HTTPS & Improve Project Conf
  aspnet-core/.gitignore
  aspnet-core/Aled.sln
  aspnet-core/docker-compose.yml
  aspnet-core/src/Aled.AuthServer/Aled.AuthServer.csproj
  aspnet-core/src/Aled.AuthServer/Program.cs
  aspnet-core/src/Aled.AuthServer/Properties/launchSettings.json
  aspnet-core/src/Aled.AuthServer/appsettings.Development.json
  aspnet-core/src/Aled.Blazor/Aled.Blazor.csproj
  aspnet-core/src/Aled.Blazor/Program.cs
  aspnet-core/src/Aled.Blazor/Properties/launchSettings.json
  aspnet-core/src/Aled.Blazor/appsettings.Development.json
  aspnet-core/src/Aled.Blazor/appsettings.json
  aspnet-core/src/Aled.DbMigrator/Aled.DbMigrator.csproj
  aspnet-core/src/Aled.DbMigrator/Program.cs
  aspnet-core/src/Aled.DbMigrator/appsettings.json
  aspnet-core/src/Aled.HttpApi.Client/updateProxy.sh
  aspnet-core/src/Aled.HttpApi.Host/Aled.HttpApi.Host.csproj
  aspnet-core/src/Aled.HttpApi.Host/Program.cs
  aspnet-core/src/Aled.HttpApi.Host/Properties/launchSettings.json
  aspnet-core/src/Aled.HttpApi.Host/appsettings.Development.json
  aspnet-core/src/Aled.HttpApi.Host/appsettings.json
  aspnet-core/ssl/cert.conf
  aspnet-core/ssl/cert.crt
  aspnet-core/ssl/cert.pem
  aspnet-core/ssl/key.pem
  aspnet-core/test/Aled.HttpApi.Client.ConsoleTestApp/Aled.HttpApi.Client.ConsoleTestApp.csproj
  aspnet-core/test/Aled.HttpApi.Client.ConsoleTestApp/Program.cs
  aspnet-core/test/Aled.HttpApi.Client.ConsoleTestApp/appsettings.json
  react-native/.gitignore
  react-native/Environment.js
Labels: bug, Backend, FrontEnd

#31 feature #30 mise à jour de la logique pour la gestion de l'inventaire
  aspnet-core/Aled.sln.DotSettings
  aspnet-core/README.md
  aspnet-core/src/Aled.Application.Contracts/Aled.Application.Contracts.csproj
  aspnet-core/src/Aled.Application.Contracts/Inventories/IInventoryAppService.cs
  aspnet-core/src/Aled.Application.Contracts/Products/Dtos/AddProductDto.cs
  aspnet-core/src/Aled.Application.Contracts/Products/Dtos/ProductDto.cs
  aspnet-core/src/Aled.Application.Contracts/Products/Dtos/RemoveProductDto.cs
  aspnet-core/src/Aled.Application/AledApplicationAutoMapperProfile.cs
  aspnet-core/src/Aled.Application/Inventories/InventoryAppService.cs
  aspnet-core/src/Aled.Blazor/Pages/Index.razor
  aspnet-core/src/Aled.DbMigrator/appsettings.json
  aspnet-core/src/Aled.Domain.Shared/AledModuleExtensionConfigurator.cs
  aspnet-core/src/Aled.Domain/AggregateRoots/Inventories/Inventory.cs
  aspnet-core/src/Aled.Domain/Aled.Domain.csproj
  aspnet-core/src/Aled.Domain/Data/AledDbMigrationService.cs
  aspnet-core/src/Aled.Domain/DataSeeders/InventoryDataSeedContributor.cs
  aspnet-core/src/Aled.Domain/Entities/Products/Product.cs
  aspnet-core/src/Aled.Domain/Events/Identity/LocalIdentityUserChangeEventHandler.cs
  aspnet-core/src/Aled.Domain/Managers/Inventories/IInventoryManager.cs
  aspnet-core/src/Aled.Domain/Managers/Inventories/InventoryManager.cs
  aspnet-core/src/Aled.Domain/Managers/OpenFoodFacts/OpenFoodFactService.cs
  aspnet-core/src/Aled.Domain/OpenIddict/OpenIddictDataSeedContributor.cs
  aspnet-core/src/Aled.Domain/Repositories/Inventories/IInventoryRepository.cs
  aspnet-core/src/Aled.Domain/Services/Inventories/IInventoryService.cs
  aspnet-core/src/Aled.Domain/Services/Inventories/InventoryService.cs
  aspnet-core/src/Aled.Domain/Services/OpenFoodFacts/OpenFoodFactService.cs
  aspnet-core/src/Aled.EntityFrameworkCore/EfCoreRepositories/Inventories/EfCoreInventoryRepository.cs
  aspnet-core/src/Aled.EntityFrameworkCore/EntityFrameworkCore/AledDbContext.cs
  aspnet-core/src/Aled.EntityFrameworkCore/EntityFrameworkCore/AledEfCoreEntityExtensionMappings.cs
  aspnet-core/src/Aled.EntityFrameworkCore/Migrations/20240722151910_Initial.Designer.cs
  aspnet-core/src/Aled.EntityFrameworkCore/Migrations/20240722151910_Initial.cs
  aspnet-core/src/Aled.EntityFrameworkCore/Migrations/AledDbContextModelSnapshot.cs
  aspnet-core/test/Aled.Application.Tests/Inventories/InventoryAppServiceTests.cs
  aspnet-core/test/Aled.Application.Tests/Samples/SampleAppServiceTests.cs
  aspnet-core/test/Aled.Domain.Tests/Inventories/InventoryDomainTests.cs
  aspnet-core/test/Aled.Domain.Tests/Samples/SampleDomainTests.cs
  aspnet-core/test/Aled.EntityFrameworkCore.Tests/EntityFrameworkCore/Applications/EfCoreInventoryAppServiceTests.cs
  aspnet-core/test/Aled.EntityFrameworkCore.Tests/EntityFrameworkCore/Applications/EfCoreSampleAppServiceTests.cs
  aspnet-core/test/Aled.EntityFrameworkCore.Tests/EntityFrameworkCore/Domains/EfCoreInventoryDomainTests.cs
  aspnet-core/test/Aled.EntityFrameworkCore.Tests/EntityFrameworkCore/Domains/EfCoreSampleDomainTests.cs
  aspnet-core/test/Aled.EntityFrameworkCore.Tests/EntityFrameworkCore/Inventories/EfCoreInventoryRepositoryTests.cs
  aspnet-core/test/Aled.TestBase/Aled.TestBase.csproj
  aspnet-core/test/Aled.TestBase/AledTestDataSeedContributor.cs
Labels: enhancement, Backend
